// examples/react-vite/src/frames/stateful/UserCard.g.tsx
import { createGScopeHook, type GFrames } from "@runelight/react/runtime"

type UserCardProps = {
  userId: string
}

type UserCardScope =
  | { status: "loading" }
  | { status: "error"; message: string; onRetry: () => void }
  | { status: "ready"; name: string; role: string; lastSeen: string }

function useRealUserCardScope(_props: UserCardProps): UserCardScope {
  return { status: "loading" }
}

const useUserCardGScope = createGScopeHook(useRealUserCardScope)

export default function UserCard(props: UserCardProps) {
  const scope = useUserCardGScope(props)

  if (scope.status === "loading") {
    return (
      <section className="user-card" data-state="loading">
        <span className="user-card-eyebrow">{props.userId}</span>
        <h1>Loading user...</h1>
        <div className="user-card-skeleton" />
      </section>
    )
  }

  if (scope.status === "error") {
    return (
      <section className="user-card" data-state="error">
        <span className="user-card-eyebrow">{props.userId}</span>
        <h1>User failed to load</h1>
        <p>{scope.message}</p>
        <button onClick={scope.onRetry}>Retry</button>
      </section>
    )
  }

  return (
    <section className="user-card" data-state="ready">
      <span className="user-card-eyebrow">{props.userId}</span>
      <h1>{scope.name}</h1>
      <p>{scope.role}</p>
      <strong>{scope.lastSeen}</strong>
    </section>
  )
}

UserCard.frames = {
  loading: {
    description: "loading frame",
    props: { userId: "user_1" },
    scope: { status: "loading" },
  },
  error: {
    description: "error frame",
    props: { userId: "user_1" },
    scope: { status: "error", message: "The profile service timed out.", onRetry: () => {} },
  },
  ready: {
    description: "ready frame",
    props: { userId: "user_42" },
    scope: {
      status: "ready",
      name: "Ada Lovelace",
      role: "Preview systems engineer",
      lastSeen: "Active 3 minutes ago",
    },
  },
} satisfies GFrames<UserCardProps, UserCardScope>

// examples/vue-vite/src/components/UserCard.g.vue
<template>
  <article class="user-card" :data-state="status">
    <p class="eyebrow">{{ props.userId }}</p>
    <h1 v-if="status === 'loading'">Loading profile</h1>
    <section v-else-if="status === 'error'">
      <h1>Profile failed</h1>
      <p>{{ message }}</p>
    </section>
    <section v-else>
      <h1>{{ formatName(user.name) }}</h1>
      <p>{{ user.role }}</p>
    </section>
  </article>
</template>

<script setup lang="ts">
const props = defineProps<{ userId: string }>()
const status = "production-only"
const user = { name: "Production User", role: "Live data" }

function formatName(value: string) {
  return value.toUpperCase()
}
</script>

<g:frames>
export default {
  loading: {
    description: "loading frame",
    props: { userId: "user_loading" },
    scope: { status: "loading" },
  },
  error: {
    description: "error frame",
    props: { userId: "user_error" },
    scope: {
      status: "error",
      message: "The profile service timed out.",
    },
  },
  ready: {
    description: "ready frame",
    props: { userId: "user_42" },
    scope: {
      status: "ready",
      user: {
        name: "Ada Lovelace",
        role: "Preview systems engineer",
      },
    },
  },
}
</g:frames>
